CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_name VARCHAR(100) NOT NULL,
    subject_name VARCHAR(100) NOT NULL,
    project_topic VARCHAR(200) NOT NULL,
    deadline DATE NOT NULL,
    description TEXT NOT NULL
);

CREATE TABLE tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    stage INTEGER NOT NULL,
    stage_name VARCHAR(100) NOT NULL,
    title VARCHAR(200) NOT NULL,
    owner VARCHAR(100) NOT NULL,
    due_date DATE NOT NULL,
    done BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_tasks_project
        FOREIGN KEY (project_id) REFERENCES projects (id),
    CONSTRAINT ck_tasks_stage_positive CHECK (stage > 0)
);

CREATE INDEX idx_tasks_project_id ON tasks (project_id);
CREATE INDEX idx_tasks_risk_lookup ON tasks (done, due_date);

CREATE TABLE messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_text TEXT NOT NULL,
    ai_message TEXT NOT NULL,
    action_type VARCHAR(30) NOT NULL,
    requires_approval BOOLEAN NOT NULL,
    proposal JSONB,
    proposal_status VARCHAR(30),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_messages_action_type CHECK (
        action_type IN ('NONE', 'TASK_CREATE', 'TASK_UPDATE', 'PROJECT_UPDATE')
    ),
    CONSTRAINT ck_messages_proposal_status CHECK (
        proposal_status IS NULL
        OR proposal_status IN ('PENDING', 'APPLIED', 'SUPERSEDED')
    ),
    CONSTRAINT ck_messages_proposal_consistency CHECK (
        (
            action_type = 'NONE'
            AND requires_approval = FALSE
            AND proposal IS NULL
            AND proposal_status IS NULL
        )
        OR
        (
            action_type <> 'NONE'
            AND requires_approval = TRUE
            AND proposal IS NOT NULL
            AND proposal_status IS NOT NULL
        )
    )
);

CREATE INDEX idx_messages_pending_latest
    ON messages (proposal_status, created_at DESC, id DESC);
